name: Run linter and check types
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile

      - name: Generate nuxt types
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run typecheck
